import {
    ArrowUpDown,
    Bell,
    CircleX,
    CloudBackup,
    Container,
    Database,
    DatabaseZap,
    Download,
    Eraser,
    FileCheck,
    FileCode2,
    FileSearch,
    FolderInput,
    FolderOpen,
    FolderOutput,
    GitBranch,
    GitCommit,
    GitFork,
    GitMerge,
    Globe,
    GlobeOff,
    Hammer,
    HardDrive,
    HeartPulse,
    KeyRound,
    KeySquare,
    Layers,
    type LucideIcon,
    Milestone,
    Network,
    PackageCheck,
    PackagePlus,
    PackageX,
    Play,
    RefreshCw,
    Rocket,
    RotateCcw,
    ScanSearch,
    ScrollText,
    Server,
    ShieldCheck,
    SlidersHorizontal,
    Split,
    Square,
    SquareTerminal,
    Tag,
    Terminal,
    Timer,
    Trash2,
    Upload,
    Variable,
    Webhook,
    Workflow,
    Wrench,
} from 'lucide-react';
import { type NodeIconName } from '@nexploy/nodes/core/nodeDescriptor';

export const CATEGORY_BG_MUTED: Record<string, string> = {
    source: 'bg-blue-500/10',
    build: 'bg-orange-500/10',
    deploy: 'bg-green-500/10',
    script: 'bg-purple-500/10',
    database: 'bg-teal-500/10',
    flow: 'bg-sky-500/10',
    config: 'bg-slate-500/10',
    files: 'bg-indigo-500/10',
    integration: 'bg-rose-500/10',
    utility: 'bg-yellow-500/10',
};

export const CATEGORY_BG: Record<string, string> = {
    source: '!bg-blue-500',
    build: '!bg-orange-500',
    deploy: '!bg-green-500',
    script: '!bg-purple-500',
    database: '!bg-teal-500',
    flow: '!bg-sky-500',
    config: '!bg-slate-500',
    files: '!bg-indigo-500',
    integration: '!bg-rose-500',
    utility: '!bg-yellow-500',
};

export const CATEGORY_TEXT: Record<string, string> = {
    source: 'text-blue-600',
    build: 'text-orange-600',
    deploy: 'text-green-600',
    script: 'text-purple-600',
    database: 'text-teal-600',
    flow: 'text-sky-600',
    config: 'text-slate-600',
    files: 'text-indigo-600',
    integration: 'text-rose-600',
    utility: 'text-yellow-600',
};

export const CATEGORY_HEX: Record<string, string> = {
    source: '#2b7fff',
    build: '#ff6900',
    deploy: '#00c951',
    script: '#a855f7',
    database: '#14b8a6',
    flow: '#0ea5e9',
    config: '#64748b',
    files: '#6366f1',
    integration: '#f43f5e',
    utility: '#efb100',
};

export const CATEGORY_BORDER: Record<string, string> = {
    source: 'border-blue-500',
    build: 'border-orange-500',
    deploy: 'border-green-500',
    script: 'border-purple-500',
    database: 'border-teal-500',
    flow: 'border-sky-500',
    config: 'border-slate-500',
    files: 'border-indigo-500',
    integration: 'border-rose-500',
    utility: 'border-yellow-500',
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
    source: GitBranch,
    build: Hammer,
    deploy: Rocket,
    script: Terminal,
    database: Database,
    flow: Workflow,
    config: SlidersHorizontal,
    files: FolderOpen,
    integration: Webhook,
    utility: Wrench,
};

export const ICON_NAME_MAP: Record<NodeIconName, LucideIcon> = {
    ArrowUpDown,
    Bell,
    CircleX,
    CloudBackup,
    Container,
    DatabaseZap,
    Download,
    Eraser,
    FileCheck,
    FileSearch,
    FolderInput,
    FolderOutput,
    GitBranch,
    GitCommit,
    GitFork,
    GitMerge,
    Globe,
    GlobeOff,
    Hammer,
    HardDrive,
    HeartPulse,
    KeyRound,
    KeySquare,
    Layers,
    Milestone,
    Network,
    PackageCheck,
    PackagePlus,
    PackageX,
    Play,
    RefreshCw,
    Rocket,
    RotateCcw,
    ScanSearch,
    ScrollText,
    Server,
    ShieldCheck,
    Split,
    Square,
    SquareTerminal,
    Tag,
    Terminal,
    Timer,
    Trash2,
    Upload,
    Variable,
    Webhook,
    Workflow,
};
